In [113]:

import csv
import pandas as pd

In [114]:
df = pd.read_csv ("base_manut.csv").to_csv
df = pd.read_csv('base_manut.csv', sep=';', encoding='UTF-8')
df.head()

,work_order_id,equipment_id,equipment_type,fabricante,modelo,prioridade,tipo_manutencao,status,data_abertura,data_inicio,...,tempo_parada_h,horas_planejadas_em_aberto,equipe_capacidade_h_dia,tempo_disponivel_h,tempo_operado_h,local,turno,custo_estimado,responsavel,observacoes
0,WO0001,H009,Colhedora de cana,Valtra,Val-288,Alta,Corretiva,Aberta,2023-10-02 05:34,NaN,...,"22,2","5,4",12,"23,1","0,9",Fazenda B,Tarde,21359,Srta. Catarina Costela,Laudantium voluptates fuga quasi labore. Susci...
1,WO0002,H006,Colhedora de cana,Valtra,Val-290,Alta,Preditiva,Concluída,2023-03-20 08:27,2023-03-20 15:22,...,"6,8","31,5",16,"16,4","9,6",Fazenda A,Manhã,28680,Daniel Sampaio,Incidunt sequi incidunt. Dolorem dolore hic no...
2,WO0003,H013,Colhedora de cana,AGCO,AGC-457,Alta,Preventiva,Concluída,2026-01-25 19:15,2026-01-27 17:41,...,"9,4","35,1",14,"13,8","4,4",Fazenda B,Manhã,4242,Caroline Siqueira,Itaque inventore nulla beatae inventore. Iusto...
3,WO0004,H010,Colhedora de cana,AGCO,AGC-327,Baixa,Corretiva,Aberta,2023-09-12 04:54,NaN,...,"1,6","41,7",15,"14,5","12,9",Fazenda B,Tarde,1408,Joaquim Peixoto,Qui fugiat sunt eos velit maiores veniam.\nDol...
4,WO0005,H008,Colhedora de cana,Valtra,Val-318,Baixa,Preditiva,Concluída,2023-10-02 17:17,2023-10-03 10:11,...,10,"39,4",16,"21,2","11,2",Fazenda A,Noite,7395,Anthony Lima,NaN

In [115]:
df.tail()

,work_order_id,equipment_id,equipment_type,fabricante,modelo,prioridade,tipo_manutencao,status,data_abertura,data_inicio,...,tempo_parada_h,horas_planejadas_em_aberto,equipe_capacidade_h_dia,tempo_disponivel_h,tempo_operado_h,local,turno,custo_estimado,responsavel,observacoes
995,WO0996,H005,Colhedora de cana,Case IH,Cas-206,Média,Corretiva,Em Andamento,2026-02-19 23:13,2026-02-20 16:44,...,"11,8","24,6",7,"23,8",12,Fazenda B,Noite,27310,Gabriela Jesus,NaN
996,WO0997,T009,Trator,Case IH,Cas-T173,Alta,Preventiva,Aberta,2024-02-02 12:21,NaN,...,"1,5","45,5",14,"9,8","8,3",Fazenda A,Manhã,2544,Mathias Araújo,NaN
997,WO0998,T009,Trator,Case IH,Cas-T173,Baixa,Preditiva,Em Andamento,2026-02-22 20:36,2026-02-23 17:53,...,4,"13,9",16,"12,9","8,9",Fazenda B,Manhã,1216,Ravy Ribeiro,Temporibus magnam recusandae. Odio nihil minus...
998,WO0999,H002,Colhedora de cana,New Holland,New-267,Baixa,Preventiva,Aberta,2023-07-10 13:42,NaN,...,"0,4","32,4",6,"18,7","18,3",Fazenda A,Tarde,1011,Antonella Rezende,NaN
999,WO1000,H001,Colhedora de cana,Case IH,Cas-500,Média,Preditiva,Concluída,2024-01-31 10:35,2024-01-31 14:36,...,"14,2","16,3",6,"15,5","1,3",Armazém,Manhã,27699,Ana Julia Vieira,NaN

In [116]:
cols = ['modelo','prioridade','status']
df[cols]

       modelo prioridade        status
0     Val-288       Alta        Aberta
1     Val-290       Alta     Concluída
2     AGC-457       Alta     Concluída
3     AGC-327      Baixa        Aberta
4     Val-318      Baixa     Concluída
..        ...        ...           ...
995   Cas-206      Média  Em Andamento
996  Cas-T173       Alta        Aberta
997  Cas-T173      Baixa  Em Andamento
998   New-267      Baixa        Aberta
999   Cas-500      Média     Concluída

[1000 rows x 3 columns]

In [117]:
#df["prioridade"]="Alta"
#df

In [118]:
df['tempo_parada_h'] = (df['tempo_parada_h']
                        .astype(str)
                        .str.replace(',', '.', regex=False)
                        .astype(float))
df

,work_order_id,equipment_id,equipment_type,fabricante,modelo,prioridade,tipo_manutencao,status,data_abertura,data_inicio,...,tempo_parada_h,horas_planejadas_em_aberto,equipe_capacidade_h_dia,tempo_disponivel_h,tempo_operado_h,local,turno,custo_estimado,responsavel,observacoes
0,WO0001,H009,Colhedora de cana,Valtra,Val-288,Alta,Corretiva,Aberta,2023-10-02 05:34,NaN,...,22.2,"5,4",12,"23,1","0,9",Fazenda B,Tarde,21359,Srta. Catarina Costela,Laudantium voluptates fuga quasi labore. Susci...
1,WO0002,H006,Colhedora de cana,Valtra,Val-290,Alta,Preditiva,Concluída,2023-03-20 08:27,2023-03-20 15:22,...,6.8,"31,5",16,"16,4","9,6",Fazenda A,Manhã,28680,Daniel Sampaio,Incidunt sequi incidunt. Dolorem dolore hic no...
2,WO0003,H013,Colhedora de cana,AGCO,AGC-457,Alta,Preventiva,Concluída,2026-01-25 19:15,2026-01-27 17:41,...,9.4,"35,1",14,"13,8","4,4",Fazenda B,Manhã,4242,Caroline Siqueira,Itaque inventore nulla beatae inventore. Iusto...
3,WO0004,H010,Colhedora de cana,AGCO,AGC-327,Baixa,Corretiva,Aberta,2023-09-12 04:54,NaN,...,1.6,"41,7",15,"14,5","12,9",Fazenda B,Tarde,1408,Joaquim Peixoto,Qui fugiat sunt eos velit maiores veniam.\nDol...
4,WO0005,H008,Colhedora de cana,Valtra,Val-318,Baixa,Preditiva,Concluída,2023-10-02 17:17,2023-10-03 10:11,...,10.0,"39,4",16,"21,2","11,2",Fazenda A,Noite,7395,Anthony Lima,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,WO0996,H005,Colhedora de cana,Case IH,Cas-206,Média,Corretiva,Em Andamento,2026-02-19 23:13,2026-02-20 16:44,...,11.8,"24,6",7,"23,8",12,Fazenda B,Noite,27310,Gabriela Jesus,NaN
996,WO0997,T009,Trator,Case IH,Cas-T173,Alta,Preventiva,Aberta,2024-02-02 12:21,NaN,...,1.5,"45,5",14,"9,8","8,3",Fazenda A,Manhã,2544,Mathias Araújo,NaN
997,WO0998,T009,Trator,Case IH,Cas-T173,Baixa,Preditiva,Em Andamento,2026-02-22 20:36,2026-02-23 17:53,...,4.0,"13,9",16,"12,9","8,9",Fazenda B,Manhã,1216,Ravy Ribeiro,Temporibus magnam recusandae. Odio nihil minus...
998,WO0999,H002,Colhedora de cana,New Holland,New-267,Baixa,Preventiva,Aberta,2023-07-10 13:42,NaN,...,0.4,"32,4",6,"18,7","18,3",Fazenda A,Tarde,1011,Antonella Rezende,NaN
999,WO1000,H001,Colhedora de cana,Case IH,Cas-500,Média,Preditiva,Concluída,2024-01-31 10:35,2024-01-31 14:36,...,14.2,"16,3",6,"15,5","1,3",Armazém,Manhã,27699,Ana Julia Vieira,NaN

In [119]:
df.head(3)

,work_order_id,equipment_id,equipment_type,fabricante,modelo,prioridade,tipo_manutencao,status,data_abertura,data_inicio,...,tempo_parada_h,horas_planejadas_em_aberto,equipe_capacidade_h_dia,tempo_disponivel_h,tempo_operado_h,local,turno,custo_estimado,responsavel,observacoes
0,WO0001,H009,Colhedora de cana,Valtra,Val-288,Alta,Corretiva,Aberta,2023-10-02 05:34,NaN,...,22.2,"5,4",12,"23,1","0,9",Fazenda B,Tarde,21359,Srta. Catarina Costela,Laudantium voluptates fuga quasi labore. Susci...
1,WO0002,H006,Colhedora de cana,Valtra,Val-290,Alta,Preditiva,Concluída,2023-03-20 08:27,2023-03-20 15:22,...,6.8,"31,5",16,"16,4","9,6",Fazenda A,Manhã,28680,Daniel Sampaio,Incidunt sequi incidunt. Dolorem dolore hic no...
2,WO0003,H013,Colhedora de cana,AGCO,AGC-457,Alta,Preventiva,Concluída,2026-01-25 19:15,2026-01-27 17:41,...,9.4,"35,1",14,"13,8","4,4",Fazenda B,Manhã,4242,Caroline Siqueira,Itaque inventore nulla beatae inventore. Iusto...

In [120]:
df.dtypes

work_order_id                     str
equipment_id                      str
equipment_type                    str
fabricante                        str
modelo                            str
prioridade                        str
tipo_manutencao                   str
status                            str
data_abertura                     str
data_inicio                       str
data_fim                          str
tempo_reparo_min                int64
causa_raiz                        str
componente_afetado                str
severidade_falha                int64
tempo_parada_h                float64
horas_planejadas_em_aberto        str
equipe_capacidade_h_dia         int64
tempo_disponivel_h                str
tempo_operado_h                   str
local                             str
turno                             str
custo_estimado                  int64
responsavel                       str
observacoes                       str
dtype: object

In [121]:
cols = ['data_abertura','data_inicio','data_fim']
df[cols] = df[cols].apply(lambda s: pd.to_datetime(s, errors='coerce', dayfirst=True))
df.head(3)

C:\Users\vanes\AppData\Local\Temp\ipykernel_13564\331753862.py:2: UserWarning: Parsing dates in %Y-%m-%d %H:%M format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df[cols] = df[cols].apply(lambda s: pd.to_datetime(s, errors='coerce', dayfirst=True))
C:\Users\vanes\AppData\Local\Temp\ipykernel_13564\331753862.py:2: UserWarning: Parsing dates in %Y-%m-%d %H:%M format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df[cols] = df[cols].apply(lambda s: pd.to_datetime(s, errors='coerce', dayfirst=True))

,work_order_id,equipment_id,equipment_type,fabricante,modelo,prioridade,tipo_manutencao,status,data_abertura,data_inicio,...,tempo_parada_h,horas_planejadas_em_aberto,equipe_capacidade_h_dia,tempo_disponivel_h,tempo_operado_h,local,turno,custo_estimado,responsavel,observacoes
0,WO0001,H009,Colhedora de cana,Valtra,Val-288,Alta,Corretiva,Aberta,2023-02-10 05:34:00,NaT,...,22.2,"5,4",12,"23,1","0,9",Fazenda B,Tarde,21359,Srta. Catarina Costela,Laudantium voluptates fuga quasi labore. Susci...
1,WO0002,H006,Colhedora de cana,Valtra,Val-290,Alta,Preditiva,Concluída,NaT,2023-03-20 15:22:00,...,6.8,"31,5",16,"16,4","9,6",Fazenda A,Manhã,28680,Daniel Sampaio,Incidunt sequi incidunt. Dolorem dolore hic no...
2,WO0003,H013,Colhedora de cana,AGCO,AGC-457,Alta,Preventiva,Concluída,NaT,2026-01-27 17:41:00,...,9.4,"35,1",14,"13,8","4,4",Fazenda B,Manhã,4242,Caroline Siqueira,Itaque inventore nulla beatae inventore. Iusto...

In [122]:
df.dtypes

work_order_id                            str
equipment_id                             str
equipment_type                           str
fabricante                               str
modelo                                   str
prioridade                               str
tipo_manutencao                          str
status                                   str
data_abertura                 datetime64[us]
data_inicio                   datetime64[us]
data_fim                      datetime64[us]
tempo_reparo_min                       int64
causa_raiz                               str
componente_afetado                       str
severidade_falha                       int64
tempo_parada_h                       float64
horas_planejadas_em_aberto               str
equipe_capacidade_h_dia                int64
tempo_disponivel_h                       str
tempo_operado_h                          str
local                                    str
turno                                    str
custo_estimado                         int64
responsavel                              str
observacoes                              str
dtype: object

In [123]:
df[cols_temp] = df[cols_temp].replace(',', '.', regex=True)
df[cols_temp] = df[cols_temp].apply(pd.to_numeric, errors='coerce').astype('Float64')
df

,work_order_id,equipment_id,equipment_type,fabricante,modelo,prioridade,tipo_manutencao,status,data_abertura,data_inicio,...,tempo_parada_h,horas_planejadas_em_aberto,equipe_capacidade_h_dia,tempo_disponivel_h,tempo_operado_h,local,turno,custo_estimado,responsavel,observacoes
0,WO0001,H009,Colhedora de cana,Valtra,Val-288,Alta,Corretiva,Aberta,2023-02-10 05:34:00,NaT,...,22.2,5.4,12.0,23.1,0.9,Fazenda B,Tarde,21359.0,Srta. Catarina Costela,Laudantium voluptates fuga quasi labore. Susci...
1,WO0002,H006,Colhedora de cana,Valtra,Val-290,Alta,Preditiva,Concluída,NaT,2023-03-20 15:22:00,...,6.8,31.5,16.0,16.4,9.6,Fazenda A,Manhã,28680.0,Daniel Sampaio,Incidunt sequi incidunt. Dolorem dolore hic no...
2,WO0003,H013,Colhedora de cana,AGCO,AGC-457,Alta,Preventiva,Concluída,NaT,2026-01-27 17:41:00,...,9.4,35.1,14.0,13.8,4.4,Fazenda B,Manhã,4242.0,Caroline Siqueira,Itaque inventore nulla beatae inventore. Iusto...
3,WO0004,H010,Colhedora de cana,AGCO,AGC-327,Baixa,Corretiva,Aberta,2023-12-09 04:54:00,NaT,...,1.6,41.7,15.0,14.5,12.9,Fazenda B,Tarde,1408.0,Joaquim Peixoto,Qui fugiat sunt eos velit maiores veniam.\nDol...
4,WO0005,H008,Colhedora de cana,Valtra,Val-318,Baixa,Preditiva,Concluída,2023-02-10 17:17:00,2023-10-03 10:11:00,...,10.0,39.4,16.0,21.2,11.2,Fazenda A,Noite,7395.0,Anthony Lima,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,WO0996,H005,Colhedora de cana,Case IH,Cas-206,Média,Corretiva,Em Andamento,NaT,2026-02-20 16:44:00,...,11.8,24.6,7.0,23.8,12.0,Fazenda B,Noite,27310.0,Gabriela Jesus,NaN
996,WO0997,T009,Trator,Case IH,Cas-T173,Alta,Preventiva,Aberta,2024-02-02 12:21:00,NaT,...,1.5,45.5,14.0,9.8,8.3,Fazenda A,Manhã,2544.0,Mathias Araújo,NaN
997,WO0998,T009,Trator,Case IH,Cas-T173,Baixa,Preditiva,Em Andamento,NaT,2026-02-23 17:53:00,...,4.0,13.9,16.0,12.9,8.9,Fazenda B,Manhã,1216.0,Ravy Ribeiro,Temporibus magnam recusandae. Odio nihil minus...
998,WO0999,H002,Colhedora de cana,New Holland,New-267,Baixa,Preventiva,Aberta,2023-10-07 13:42:00,NaT,...,0.4,32.4,6.0,18.7,18.3,Fazenda A,Tarde,1011.0,Antonella Rezende,NaN
999,WO1000,H001,Colhedora de cana,Case IH,Cas-500,Média,Preditiva,Concluída,NaT,2024-01-31 14:36:00,...,14.2,16.3,6.0,15.5,1.3,Armazém,Manhã,27699.0,Ana Julia Vieira,NaN

In [124]:
df.dtypes

work_order_id                            str
equipment_id                             str
equipment_type                           str
fabricante                               str
modelo                                   str
prioridade                               str
tipo_manutencao                          str
status                                   str
data_abertura                 datetime64[us]
data_inicio                   datetime64[us]
data_fim                      datetime64[us]
tempo_reparo_min                       int64
causa_raiz                               str
componente_afetado                       str
severidade_falha                       int64
tempo_parada_h                       Float64
horas_planejadas_em_aberto           Float64
equipe_capacidade_h_dia              Float64
tempo_disponivel_h                   Float64
tempo_operado_h                      Float64
local                                    str
turno                                    str
custo_estimado                       Float64
responsavel                              str
observacoes                              str
dtype: object

In [125]:
df.head(3)

,work_order_id,equipment_id,equipment_type,fabricante,modelo,prioridade,tipo_manutencao,status,data_abertura,data_inicio,...,tempo_parada_h,horas_planejadas_em_aberto,equipe_capacidade_h_dia,tempo_disponivel_h,tempo_operado_h,local,turno,custo_estimado,responsavel,observacoes
0,WO0001,H009,Colhedora de cana,Valtra,Val-288,Alta,Corretiva,Aberta,2023-02-10 05:34:00,NaT,...,22.2,5.4,12.0,23.1,0.9,Fazenda B,Tarde,21359.0,Srta. Catarina Costela,Laudantium voluptates fuga quasi labore. Susci...
1,WO0002,H006,Colhedora de cana,Valtra,Val-290,Alta,Preditiva,Concluída,NaT,2023-03-20 15:22:00,...,6.8,31.5,16.0,16.4,9.6,Fazenda A,Manhã,28680.0,Daniel Sampaio,Incidunt sequi incidunt. Dolorem dolore hic no...
2,WO0003,H013,Colhedora de cana,AGCO,AGC-457,Alta,Preventiva,Concluída,NaT,2026-01-27 17:41:00,...,9.4,35.1,14.0,13.8,4.4,Fazenda B,Manhã,4242.0,Caroline Siqueira,Itaque inventore nulla beatae inventore. Iusto...

In [126]:
#filtro_prioridade = df["prioridade"] == "Alta"
#filtro_tempo_parada = df["tempo_parada_h"] > 10
#df [filtro_prioridade & filtro_tempo_parada]
#df.head(5)

In [136]:

df.groupby("prioridade")["tempo_parada_h"].mean()

prioridade
Alta      8.36384
Baixa    8.449782
Média    7.592973
Name: tempo_parada_h, dtype: Float64

In [137]:
df

,work_order_id,equipment_id,equipment_type,fabricante,modelo,prioridade,tipo_manutencao,status,data_abertura,data_inicio,...,tempo_parada_h,horas_planejadas_em_aberto,equipe_capacidade_h_dia,tempo_disponivel_h,tempo_operado_h,local,turno,custo_estimado,responsavel,observacoes
0,WO0001,H009,Colhedora de cana,Valtra,Val-288,Alta,Corretiva,Aberta,2023-02-10 05:34:00,NaT,...,22.2,5.4,12.0,23.1,0.9,Fazenda B,Tarde,21359.0,Srta. Catarina Costela,Laudantium voluptates fuga quasi labore. Susci...
1,WO0002,H006,Colhedora de cana,Valtra,Val-290,Alta,Preditiva,Concluída,NaT,2023-03-20 15:22:00,...,6.8,31.5,16.0,16.4,9.6,Fazenda A,Manhã,28680.0,Daniel Sampaio,Incidunt sequi incidunt. Dolorem dolore hic no...
2,WO0003,H013,Colhedora de cana,AGCO,AGC-457,Alta,Preventiva,Concluída,NaT,2026-01-27 17:41:00,...,9.4,35.1,14.0,13.8,4.4,Fazenda B,Manhã,4242.0,Caroline Siqueira,Itaque inventore nulla beatae inventore. Iusto...
3,WO0004,H010,Colhedora de cana,AGCO,AGC-327,Baixa,Corretiva,Aberta,2023-12-09 04:54:00,NaT,...,1.6,41.7,15.0,14.5,12.9,Fazenda B,Tarde,1408.0,Joaquim Peixoto,Qui fugiat sunt eos velit maiores veniam.\nDol...
4,WO0005,H008,Colhedora de cana,Valtra,Val-318,Baixa,Preditiva,Concluída,2023-02-10 17:17:00,2023-10-03 10:11:00,...,10.0,39.4,16.0,21.2,11.2,Fazenda A,Noite,7395.0,Anthony Lima,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,WO0996,H005,Colhedora de cana,Case IH,Cas-206,Média,Corretiva,Em Andamento,NaT,2026-02-20 16:44:00,...,11.8,24.6,7.0,23.8,12.0,Fazenda B,Noite,27310.0,Gabriela Jesus,NaN
996,WO0997,T009,Trator,Case IH,Cas-T173,Alta,Preventiva,Aberta,2024-02-02 12:21:00,NaT,...,1.5,45.5,14.0,9.8,8.3,Fazenda A,Manhã,2544.0,Mathias Araújo,NaN
997,WO0998,T009,Trator,Case IH,Cas-T173,Baixa,Preditiva,Em Andamento,NaT,2026-02-23 17:53:00,...,4.0,13.9,16.0,12.9,8.9,Fazenda B,Manhã,1216.0,Ravy Ribeiro,Temporibus magnam recusandae. Odio nihil minus...
998,WO0999,H002,Colhedora de cana,New Holland,New-267,Baixa,Preventiva,Aberta,2023-10-07 13:42:00,NaT,...,0.4,32.4,6.0,18.7,18.3,Fazenda A,Tarde,1011.0,Antonella Rezende,NaN
999,WO1000,H001,Colhedora de cana,Case IH,Cas-500,Média,Preditiva,Concluída,NaT,2024-01-31 14:36:00,...,14.2,16.3,6.0,15.5,1.3,Armazém,Manhã,27699.0,Ana Julia Vieira,NaN

In [145]:
# Ler somente as colunas necessárias da dimensão
dim = pd.read_csv("dim_equip.csv", sep=';', encoding='UTF-8')
dim.head()

,equipment_id,equipment_type,fabricante,modelo,ano_fabricacao,serie,frota,data_aquisicao,capacidade,local_base
0,H001,Colhedora de cana,Case IH,Cas-500,2017,H001-3278,Frota A,2016-08-17,Média capacidade,Fazenda Norte
1,H002,Colhedora de cana,New Holland,New-267,2019,H002-4587,Frota A,2019-02-20,Alta capacidade,Fazenda Norte
2,H003,Colhedora de cana,Valtra,Val-478,2019,H003-8492,Frota B,2018-12-28,Média capacidade,Fazenda Sul
3,H004,Colhedora de cana,Valtra,Val-228,2016,H004-4318,Frota B,2016-01-20,Baixa capacidade,Fazenda Sul
4,H005,Colhedora de cana,Case IH,Cas-206,2020,H005-5463,Frota B,2019-05-22,Alta capacidade,Fazenda Sul

In [149]:
df = df.merge(dim, on="equipment_id", how="left")
df

,work_order_id,equipment_id,equipment_type_x,fabricante_x,modelo_x,prioridade,tipo_manutencao,status,data_abertura,data_inicio,...,local_base_x,equipment_type,fabricante,modelo,ano_fabricacao_y,serie_y,frota_y,data_aquisicao_y,capacidade_y,local_base_y
0,WO0001,H009,Colhedora de cana,Valtra,Val-288,Alta,Corretiva,Aberta,2023-02-10 05:34:00,NaT,...,Armazém Principal,Colhedora de cana,Valtra,Val-288,2024,H009-8655,Frota A,2023-11-26,Alta capacidade,Armazém Principal
1,WO0002,H006,Colhedora de cana,Valtra,Val-290,Alta,Preditiva,Concluída,NaT,2023-03-20 15:22:00,...,Fazenda Sul,Colhedora de cana,Valtra,Val-290,2016,H006-3408,Frota A,2016-05-21,Baixa capacidade,Fazenda Sul
2,WO0003,H013,Colhedora de cana,AGCO,AGC-457,Alta,Preventiva,Concluída,NaT,2026-01-27 17:41:00,...,Fazenda Norte,Colhedora de cana,AGCO,AGC-457,2022,H013-1744,Frota A,2021-02-09,Alta capacidade,Fazenda Norte
3,WO0004,H010,Colhedora de cana,AGCO,AGC-327,Baixa,Corretiva,Aberta,2023-12-09 04:54:00,NaT,...,Fazenda Sul,Colhedora de cana,AGCO,AGC-327,2018,H010-6820,Frota B,2018-08-25,Alta capacidade,Fazenda Sul
4,WO0005,H008,Colhedora de cana,Valtra,Val-318,Baixa,Preditiva,Concluída,2023-02-10 17:17:00,2023-10-03 10:11:00,...,Fazenda Central,Colhedora de cana,Valtra,Val-318,2019,H008-3255,Frota A,2018-01-05,Alta capacidade,Fazenda Central
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,WO0996,H005,Colhedora de cana,Case IH,Cas-206,Média,Corretiva,Em Andamento,NaT,2026-02-20 16:44:00,...,Fazenda Sul,Colhedora de cana,Case IH,Cas-206,2020,H005-5463,Frota B,2019-05-22,Alta capacidade,Fazenda Sul
996,WO0997,T009,Trator,Case IH,Cas-T173,Alta,Preventiva,Aberta,2024-02-02 12:21:00,NaT,...,Fazenda Central,Trator,Case IH,Cas-T173,2021,T009-8441,Frota A,2019-12-19,Média capacidade,Fazenda Central
997,WO0998,T009,Trator,Case IH,Cas-T173,Baixa,Preditiva,Em Andamento,NaT,2026-02-23 17:53:00,...,Fazenda Central,Trator,Case IH,Cas-T173,2021,T009-8441,Frota A,2019-12-19,Média capacidade,Fazenda Central
998,WO0999,H002,Colhedora de cana,New Holland,New-267,Baixa,Preventiva,Aberta,2023-10-07 13:42:00,NaT,...,Fazenda Norte,Colhedora de cana,New Holland,New-267,2019,H002-4587,Frota A,2019-02-20,Alta capacidade,Fazenda Norte
999,WO1000,H001,Colhedora de cana,Case IH,Cas-500,Média,Preditiva,Concluída,NaT,2024-01-31 14:36:00,...,Fazenda Norte,Colhedora de cana,Case IH,Cas-500,2017,H001-3278,Frota A,2016-08-17,Média capacidade,Fazenda Norte

In [152]:
cols = ['data_aquisicao_y']
df[cols] = df[cols].apply(lambda s: pd.to_datetime(s, errors='coerce', dayfirst=True))
df.head(3)

C:\Users\vanes\AppData\Local\Temp\ipykernel_13564\31597910.py:2: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df[cols] = df[cols].apply(lambda s: pd.to_datetime(s, errors='coerce', dayfirst=True))

,work_order_id,equipment_id,equipment_type_x,fabricante_x,modelo_x,prioridade,tipo_manutencao,status,data_abertura,data_inicio,...,local_base_x,equipment_type,fabricante,modelo,ano_fabricacao_y,serie_y,frota_y,data_aquisicao_y,capacidade_y,local_base_y
0,WO0001,H009,Colhedora de cana,Valtra,Val-288,Alta,Corretiva,Aberta,2023-02-10 05:34:00,NaT,...,Armazém Principal,Colhedora de cana,Valtra,Val-288,2024,H009-8655,Frota A,2023-11-26,Alta capacidade,Armazém Principal
1,WO0002,H006,Colhedora de cana,Valtra,Val-290,Alta,Preditiva,Concluída,NaT,2023-03-20 15:22:00,...,Fazenda Sul,Colhedora de cana,Valtra,Val-290,2016,H006-3408,Frota A,2016-05-21,Baixa capacidade,Fazenda Sul
2,WO0003,H013,Colhedora de cana,AGCO,AGC-457,Alta,Preventiva,Concluída,NaT,2026-01-27 17:41:00,...,Fazenda Norte,Colhedora de cana,AGCO,AGC-457,2022,H013-1744,Frota A,2021-02-09,Alta capacidade,Fazenda Norte

In [153]:
df.dtypes

work_order_id                            str
equipment_id                             str
equipment_type_x                         str
fabricante_x                             str
modelo_x                                 str
prioridade                               str
tipo_manutencao                          str
status                                   str
data_abertura                 datetime64[us]
data_inicio                   datetime64[us]
data_fim                      datetime64[us]
tempo_reparo_min                       int64
causa_raiz                               str
componente_afetado                       str
severidade_falha                       int64
tempo_parada_h                       Float64
horas_planejadas_em_aberto           Float64
equipe_capacidade_h_dia              Float64
tempo_disponivel_h                   Float64
tempo_operado_h                      Float64
local                                    str
turno                                    str
custo_estimado                       Float64
responsavel                              str
observacoes                              str
equipment_type_y                         str
fabricante_y                             str
modelo_y                                 str
ano_fabricacao_x                       int64
serie_x                                  str
frota_x                                  str
data_aquisicao_x                         str
capacidade_x                             str
local_base_x                             str
equipment_type                           str
fabricante                               str
modelo                                   str
ano_fabricacao_y                       int64
serie_y                                  str
frota_y                                  str
data_aquisicao_y              datetime64[us]
capacidade_y                             str
local_base_y                             str
dtype: object

In [154]:
cal = pd.read_csv("dim_calendario.csv", sep=';', encoding='UTF-8')
cal.head()

    ano  mes  ano_mes mes_nome_pt data_inicio_mes data_fim_mes eh_safra
0  2025    2  2025-02         Fev      2025-02-01   2025-02-28      Não
1  2025    3  2025-03         Mar      2025-03-01   2025-03-31      Não
2  2025    4  2025-04         Abr      2025-04-01   2025-04-30      Não
3  2025    5  2025-05         Mai      2025-05-01   2025-05-31      Sim
4  2025    6  2025-06         Jun      2025-06-01   2025-06-30      Sim

In [155]:
cal.dtypes

ano                int64
mes                int64
ano_mes              str
mes_nome_pt          str
data_inicio_mes      str
data_fim_mes         str
eh_safra             str
dtype: object

In [159]:
cols = ['data_aquisicao_y']
df[cols] = df[cols].apply(lambda s: pd.to_datetime(s, errors='coerce', dayfirst=True))
df.head(3)

,work_order_id,equipment_id,equipment_type_x,fabricante_x,modelo_x,prioridade,tipo_manutencao,status,data_abertura,data_inicio,...,local_base_x,equipment_type,fabricante,modelo,ano_fabricacao_y,serie_y,frota_y,data_aquisicao_y,capacidade_y,local_base_y
0,WO0001,H009,Colhedora de cana,Valtra,Val-288,Alta,Corretiva,Aberta,2023-02-10 05:34:00,NaT,...,Armazém Principal,Colhedora de cana,Valtra,Val-288,2024,H009-8655,Frota A,2023-11-26,Alta capacidade,Armazém Principal
1,WO0002,H006,Colhedora de cana,Valtra,Val-290,Alta,Preditiva,Concluída,NaT,2023-03-20 15:22:00,...,Fazenda Sul,Colhedora de cana,Valtra,Val-290,2016,H006-3408,Frota A,2016-05-21,Baixa capacidade,Fazenda Sul
2,WO0003,H013,Colhedora de cana,AGCO,AGC-457,Alta,Preventiva,Concluída,NaT,2026-01-27 17:41:00,...,Fazenda Norte,Colhedora de cana,AGCO,AGC-457,2022,H013-1744,Frota A,2021-02-09,Alta capacidade,Fazenda Norte

In [ ]:
#Idade média dos equipamentos
# 1) Garantir datetime
df['data_aquisicao_y'] = pd.to_datetime(df['data_aquisicao_y'], errors='coerce', dayfirst=True)

# 2) Hoje (naïve, sem timezone)
hoje = pd.Timestamp.today().normalize()

# 3) Idade em anos
df['idade_anos'] = (hoje - df['data_aquisicao_y']).dt.days / 365.25

# 4) Idade média (ignora NaT automaticamente)
idade_media_anos = df['idade_anos'].mean()
print(f'Idade média dos equipamentos: {idade_media_anos:.2f} anos')

Idade média dos equipamentos: 7.23 anos

In [162]:
#idade media das Ordens de Serviço
# Garantir que data_abertura é datetime
df['data_abertura'] = pd.to_datetime(df['data_abertura'], errors='coerce', dayfirst=True)

# Hoje (sem timezone)
hoje = pd.Timestamp.today().normalize()

# Idade da OS em dias
df['idade_os_dias'] = (hoje - df['data_abertura']).dt.days

# Idade média (ignora NaT automaticamente)
idade_media_dias = df['idade_os_dias'].mean()
print(f'Idade média das OS: {idade_media_dias:.2f} dias')

# Opcional: preparar para gráfico (uma métrica única)
pd.DataFrame({'metric': ['idade_media_os_dias'], 'value': [idade_media_dias]}).to_csv('idade_media_os.csv', index=False)

# Se quiser ver por OS individual (work_order_id)
df[['work_order_id','idade_os_dias']].to_csv('idade_por_os.csv', index=False)

Idade média das OS: 372.75 dias

In [163]:
# 1) Garantir datas como datetime
df['data_abertura'] = pd.to_datetime(df['data_abertura'], errors='coerce', dayfirst=True)
df['data_fim']      = pd.to_datetime(df['data_fim'],      errors='coerce', dayfirst=True)

# 2) Extrair mês (timestamp do 1º dia do mês)
df['mes_abertura'] = df['data_abertura'].dt.to_period('M').dt.to_timestamp()
df['mes_fim']      = df['data_fim'].dt.to_period('M').dt.to_timestamp()

# 3) Contagens mensais
abertas = (df.groupby('mes_abertura', dropna=True)['work_order_id']
             .size().rename('os_abertas'))
encerradas = (df.loc[df['data_fim'].notna()]
                .groupby('mes_fim')['work_order_id']
                .size().rename('os_encerradas'))

# 4) Juntar e garantir todos os meses no intervalo
inicio = min(abertas.index.min(), encerradas.index.min() if not encerradas.empty else abertas.index.min())
fim    = max(abertas.index.max(), encerradas.index.max() if not encerradas.empty else abertas.index.max())
idx_meses = pd.date_range(inicio, fim, freq='MS')

mensal = (pd.concat([abertas, encerradas], axis=1)
            .reindex(idx_meses)
            .fillna(0)
            .astype(int)
            .rename_axis('mes')
            .reset_index())

print(mensal.head())
# Opcional: salvar
# mensal.to_csv('os_abertas_encerradas_mensal.csv', index=False)

         mes  os_abertas  os_encerradas
0 2023-01-01          11              9
1 2023-02-01          14              8
2 2023-03-01           8             12
3 2023-04-01           5             10
4 2023-05-01           6              3

In [170]:

# Evita divisão por zero
den = mensal['os_abertas'].replace(0, pd.NA)

mensal['taxa_encerramento'] = (mensal['os_encerradas'] / den).fillna(0).clip(lower=0)
mensal['taxa_encerramento_%'] = (mensal['taxa_encerramento'] * 100).round(2)

taxa_global = mensal['os_encerradas'].sum() / max(mensal['os_abertas'].sum(), 1)

print(mensal[['mes','os_abertas','os_encerradas','taxa_encerramento_%']].head())
print(f"Taxa de encerramento (global): {taxa_global:.2%}")
# mensal.to_csv('os_taxa_encerramento_mensal.csv', index=False)

         mes  os_abertas  os_encerradas  taxa_encerramento_%
0 2023-01-01          11              9                81.82
1 2023-02-01          14              8                57.14
2 2023-03-01           8             12               150.00
3 2023-04-01           5             10               200.00
4 2023-05-01           6              3                50.00
Taxa de encerramento (global): 83.00%

In [172]:
df

,work_order_id,equipment_id,equipment_type_x,fabricante_x,modelo_x,prioridade,tipo_manutencao,status,data_abertura,data_inicio,...,ano_fabricacao_y,serie_y,frota_y,data_aquisicao_y,capacidade_y,local_base_y,idade_anos,idade_os_dias,mes_abertura,mes_fim
0,WO0001,H009,Colhedora de cana,Valtra,Val-288,Alta,Corretiva,Aberta,2023-02-10 05:34:00,NaT,...,2024,H009-8655,Frota A,2023-11-26,Alta capacidade,Armazém Principal,2.247775,1109.0,2023-02-01,NaT
1,WO0002,H006,Colhedora de cana,Valtra,Val-290,Alta,Preditiva,Concluída,NaT,2023-03-20 15:22:00,...,2016,H006-3408,Frota A,2016-05-21,Baixa capacidade,Fazenda Sul,9.763176,NaN,NaT,2023-03-01
2,WO0003,H013,Colhedora de cana,AGCO,AGC-457,Alta,Preventiva,Concluída,NaT,2026-01-27 17:41:00,...,2022,H013-1744,Frota A,2021-02-09,Alta capacidade,Fazenda Norte,5.040383,NaN,NaT,2026-01-01
3,WO0004,H010,Colhedora de cana,AGCO,AGC-327,Baixa,Corretiva,Aberta,2023-12-09 04:54:00,NaT,...,2018,H010-6820,Frota B,2018-08-25,Alta capacidade,Fazenda Sul,7.501711,807.0,2023-12-01,NaT
4,WO0005,H008,Colhedora de cana,Valtra,Val-318,Baixa,Preditiva,Concluída,2023-02-10 17:17:00,2023-10-03 10:11:00,...,2019,H008-3255,Frota A,2018-01-05,Alta capacidade,Fazenda Central,8.136893,1109.0,2023-02-01,2023-10-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,WO0996,H005,Colhedora de cana,Case IH,Cas-206,Média,Corretiva,Em Andamento,NaT,2026-02-20 16:44:00,...,2020,H005-5463,Frota B,2019-05-22,Alta capacidade,Fazenda Sul,6.762491,NaN,NaT,NaT
996,WO0997,T009,Trator,Case IH,Cas-T173,Alta,Preventiva,Aberta,2024-02-02 12:21:00,NaT,...,2021,T009-8441,Frota A,2019-12-19,Média capacidade,Fazenda Central,6.184805,752.0,2024-02-01,NaT
997,WO0998,T009,Trator,Case IH,Cas-T173,Baixa,Preditiva,Em Andamento,NaT,2026-02-23 17:53:00,...,2021,T009-8441,Frota A,2019-12-19,Média capacidade,Fazenda Central,6.184805,NaN,NaT,NaT
998,WO0999,H002,Colhedora de cana,New Holland,New-267,Baixa,Preventiva,Aberta,2023-10-07 13:42:00,NaT,...,2019,H002-4587,Frota A,2019-02-20,Alta capacidade,Fazenda Norte,7.011636,870.0,2023-10-01,NaT
999,WO1000,H001,Colhedora de cana,Case IH,Cas-500,Média,Preditiva,Concluída,NaT,2024-01-31 14:36:00,...,2017,H001-3278,Frota A,2016-08-17,Média capacidade,Fazenda Norte,9.522245,NaN,NaT,2024-02-01

In [173]:
taxa_global

np.float64(0.83)

In [174]:
mensal

,mes,os_abertas,os_encerradas,taxa_encerramento,taxa_encerramento_%
0,2023-01-01,11,9,0.818182,81.82
1,2023-02-01,14,8,0.571429,57.14
2,2023-03-01,8,12,1.500000,150.00
3,2023-04-01,5,10,2.000000,200.00
4,2023-05-01,6,3,0.500000,50.00
5,2023-06-01,10,11,1.100000,110.00
6,2023-07-01,6,10,1.666667,166.67
7,2023-08-01,5,8,1.600000,160.00
8,2023-09-01,5,10,2.000000,200.00
9,2023-10-01,6,10,1.666667,166.67
10,2023-11-01,8,9,1.125000,112.50
11,2023-12-01,10,8,0.800000,80.00
12,2024-01-01,6,8,1.333333,133.33
13,2024-02-01,8,6,0.750000,75.00
14,2024-03-01,9,7,0.777778,77.78
15,2024-04-01,4,12,3.000000,300.00
16,2024-05-01,7,8,1.142857,114.29
17,2024-06-01,8,10,1.250000,125.00
18,2024-07-01,4,5,1.250000,125.00
19,2024-08-01,9,6,0.666667,66.67
20,2024-09-01,9,7,0.777778,77.78
21,2024-10-01,10,10,1.000000,100.00
22,2024-11-01,7,9,1.285714,128.57
23,2024-12-01,9,9,1.000000,100.00
24,2025-01-01,5,7,1.400000,140.00
25,2025-02-01,1,8,8.000000,800.00
26,2025-03-01,11,10,0.909091,90.91
27,2025-04-01,7,13,1.857143,185.71
28,2025-05-01,8,5,0.625000,62.50
29,2025-06-01,2,10,5.000000,500.00
30,2025-07-01,4,13,3.250000,325.00
31,2025-08-01,12,13,1.083333,108.33
32,2025-09-01,8,8,1.000000,100.00
33,2025-10-01,7,5,0.714286,71.43
34,2025-11-01,10,11,1.100000,110.00
35,2025-12-01,8,7,0.875000,87.50
36,2026-01-01,11,6,0.545455,54.55
37,2026-02-01,10,11,1.100000,110.00
38,2026-03-01,4,0,0.000000,0.00
39,2026-04-01,11,0,0.000000,0.00
40,2026-05-01,8,0,0.000000,0.00
41,2026-06-01,9,0,0.000000,0.00
42,2026-07-01,16,0,0.000000,0.00
43,2026-08-01,19,0,0.000000,0.00
44,2026-09-01,11,0,0.000000,0.00
45,2026-10-01,9,0,0.000000,0.00
46,2026-11-01,12,0,0.000000,0.00
47,2026-12-01,13,0,0.000000,0.00

In [175]:
abertas

mes_abertura
2023-01-01    11
2023-02-01    14
2023-03-01     8
2023-04-01     5
2023-05-01     6
2023-06-01    10
2023-07-01     6
2023-08-01     5
2023-09-01     5
2023-10-01     6
2023-11-01     8
2023-12-01    10
2024-01-01     6
2024-02-01     8
2024-03-01     9
2024-04-01     4
2024-05-01     7
2024-06-01     8
2024-07-01     4
2024-08-01     9
2024-09-01     9
2024-10-01    10
2024-11-01     7
2024-12-01     9
2025-01-01     5
2025-02-01     1
2025-03-01    11
2025-04-01     7
2025-05-01     8
2025-06-01     2
2025-07-01     4
2025-08-01    12
2025-09-01     8
2025-10-01     7
2025-11-01    10
2025-12-01     8
2026-01-01    11
2026-02-01    10
2026-03-01     4
2026-04-01    11
2026-05-01     8
2026-06-01     9
2026-07-01    16
2026-08-01    19
2026-09-01    11
2026-10-01     9
2026-11-01    12
2026-12-01    13
Name: os_abertas, dtype: int64

In [176]:
encerradas

mes_fim
2023-01-01     9
2023-02-01     8
2023-03-01    12
2023-04-01    10
2023-05-01     3
2023-06-01    11
2023-07-01    10
2023-08-01     8
2023-09-01    10
2023-10-01    10
2023-11-01     9
2023-12-01     8
2024-01-01     8
2024-02-01     6
2024-03-01     7
2024-04-01    12
2024-05-01     8
2024-06-01    10
2024-07-01     5
2024-08-01     6
2024-09-01     7
2024-10-01    10
2024-11-01     9
2024-12-01     9
2025-01-01     7
2025-02-01     8
2025-03-01    10
2025-04-01    13
2025-05-01     5
2025-06-01    10
2025-07-01    13
2025-08-01    13
2025-09-01     8
2025-10-01     5
2025-11-01    11
2025-12-01     7
2026-01-01     6
2026-02-01    11
Name: os_encerradas, dtype: int64